using System.Linq;
using ActivityMockGenerator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Temporalio.Workflows;
using Xunit;

namespace Generator.Tests.ActivityMockGenerator;

public class ActivityMockGeneratorTests
{
    [Fact]
    public void GeneratesCorrectOutputForBasicActivity()
    {
        const string input = """
                             using NSubstitute;
                             using Temporalio.Activities;
                             using Temporalio.Generators.Workflows;

                             namespace Generator.Tests.ActivityMockGenerator;

                             [GenerateNSubstituteMocks]
                             public partial class TestMocks : ActivityMockBase<TestActivities>
                             {
                             }
                             
                             public class TestActivities
                             {
                                 [Activity]
                                 public Task<string> RunAsync()
                                 {
                                     return Task.FromResult("hello");
                                 }
                             }
                             
                             """;

        const string expectedOutput = """
                                      //------------------------------------------------------------------------------
                                      // <auto-generated>
                                      //     This code was generated.
                                      //
                                      //     Changes to this file may cause incorrect behavior and will be lost if
                                      //     the code is regenerated.
                                      // </auto-generated>
                                      //------------------------------------------------------------------------------
                                  
                                      using NSubstitute;
                                      using Temporalio.Activities;
                                  
                                      namespace Generator.Tests.ActivityMockGenerator
                                      {
                                          public partial class TestMocks
                                          {
                                              public Func<Task<string>> MockRunAsync =
                                                  Substitute.For<Func<Task<string>>>();
                                  
                                              [Activity]
                                              public Task<string> RunAsync()
                                              {
                                                  return MockRunAsync();
                                              }
                                          }
                                      }

                                      """;

        RunTest(input, expectedOutput, "TestMocks");
    }
    
    
    [Fact]
    public void GeneratesCorrectOutputForActivityWithParameters()
    {
        const string input = """
                             using NSubstitute;
                             using Temporalio.Activities;
                             using Temporalio.Generators.Workflows;

                             namespace Generator.Tests.ActivityMockGenerator;

                             [GenerateNSubstituteMocks]
                             public partial class TestMocks : ActivityMockBase<TestActivities>
                             {
                             }
                             
                             public class TestActivities
                             {
                                 [Activity]
                                 public Task<string> RunAsync(string input1, TestRecord input2)
                                 {
                                     return Task.FromResult("hello");
                                 }
                             }
                             
                             public record TestRecord();
                             
                             """;

        const string expectedOutput = """
                                      //------------------------------------------------------------------------------
                                      // <auto-generated>
                                      //     This code was generated.
                                      //
                                      //     Changes to this file may cause incorrect behavior and will be lost if
                                      //     the code is regenerated.
                                      // </auto-generated>
                                      //------------------------------------------------------------------------------
                                  
                                      using System;
                                      using Generator.Tests.ActivityMockGenerator;
                                      using NSubstitute;
                                      using Temporalio.Activities;
                                  
                                      namespace Generator.Tests.ActivityMockGenerator
                                      {
                                          public partial class TestMocks
                                          {
                                              public Func<string, Generator.Tests.ActivityMockGenerator.TestRecord, Task<string>> MockRunAsync =
                                                  Substitute.For<Func<string, Generator.Tests.ActivityMockGenerator.TestRecord, Task<string>>>();
                                  
                                              [Activity]
                                              public Task<string> RunAsync(string input1, Generator.Tests.ActivityMockGenerator.TestRecord input2)
                                              {
                                                  return MockRunAsync(input1, input2);
                                              }
                                          }
                                      }

                                      """;

        RunTest(input, expectedOutput, "TestMocks");
    }
    
    [Fact]
    public void GeneratesCorrectOutputForActivityWithTaskReturnType()
    {
        const string input = """
                             using NSubstitute;
                             using Temporalio.Activities;
                             using Temporalio.Generators.Workflows;

                             namespace Generator.Tests.ActivityMockGenerator;

                             [GenerateNSubstituteMocks]
                             public partial class TestMocks : ActivityMockBase<TestActivities>
                             {
                             }
                             
                             public class TestActivities
                             {
                                 [Activity]
                                 public Task RunAsync()
                                 {
                                     return Task.CompletedTask;
                                 }
                             }
                             
                             """;

        const string expectedOutput = """
                                      //------------------------------------------------------------------------------
                                      // <auto-generated>
                                      //     This code was generated.
                                      //
                                      //     Changes to this file may cause incorrect behavior and will be lost if
                                      //     the code is regenerated.
                                      // </auto-generated>
                                      //------------------------------------------------------------------------------
                                  
                                      using NSubstitute;
                                      using Temporalio.Activities;
                                  
                                      namespace Generator.Tests.ActivityMockGenerator
                                      {
                                          public partial class TestMocks
                                          {
                                              public Func<Task> MockRunAsync =
                                                  Substitute.For<Func<Task>>();
                                  
                                              [Activity]
                                              public Task RunAsync()
                                              {
                                                  return MockRunAsync();
                                              }
                                          }
                                      }

                                      """;

        RunTest(input, expectedOutput, "TestMocks");
    }
    
    [Fact]
    public void GeneratesCorrectOutputForActivityWithTaskTRecordReturnType()
    {
        const string input = """
                             using NSubstitute;
                             using Temporalio.Activities;
                             using Temporalio.Generators.Workflows;

                             namespace Generator.Tests.ActivityMockGenerator;

                             [GenerateNSubstituteMocks]
                             public partial class TestMocks : ActivityMockBase<TestActivities>
                             {
                             }
                             
                             public class TestActivities
                             {
                                 [Activity]
                                 public Task<TestRecord> RunAsync()
                                 {
                                     return Task.FromResult(new TestRecord());
                                 }
                             }
                             
                             public record TestRecord();
                             
                             """;

        const string expectedOutput = """
                                      //------------------------------------------------------------------------------
                                      // <auto-generated>
                                      //     This code was generated.
                                      //
                                      //     Changes to this file may cause incorrect behavior and will be lost if
                                      //     the code is regenerated.
                                      // </auto-generated>
                                      //------------------------------------------------------------------------------
                                      
                                      using NSubstitute;
                                      using Temporalio.Activities;
                                  
                                      namespace Generator.Tests.ActivityMockGenerator
                                      {
                                          public partial class TestMocks
                                          {
                                              public Func<Task<Generator.Tests.ActivityMockGenerator.TestRecord>> MockRunAsync =
                                                  Substitute.For<Func<Task<Generator.Tests.ActivityMockGenerator.TestRecord>>>();
                                  
                                              [Activity]
                                              public Task<Generator.Tests.ActivityMockGenerator.TestRecord> RunAsync()
                                              {
                                                  return MockRunAsync();
                                              }
                                          }
                                      }

                                      """;

        RunTest(input, expectedOutput, "TestMocks");
    }
    
    [Fact]
    public void GeneratesCorrectOutputForClassWithMultipleActivities()
    {
        const string input = """
                             using NSubstitute;
                             using Temporalio.Activities;
                             using Temporalio.Generators.Workflows;

                             namespace Generator.Tests.ActivityMockGenerator;

                             [GenerateNSubstituteMocks]
                             public partial class TestMocks : ActivityMockBase<TestActivities>
                             {
                             }
                             
                             public class TestActivities
                             {
                                 [Activity]
                                 public Task RunAsync()
                                 {
                                     return Task.CompletedTask;
                                 }
                                 
                                 [Activity]
                                 public Task RunAsync2()
                                 {
                                     return Task.CompletedTask;
                                 }
                             }
                             
                             """;

        const string expectedOutput = """
                                      //------------------------------------------------------------------------------
                                      // <auto-generated>
                                      //     This code was generated.
                                      //
                                      //     Changes to this file may cause incorrect behavior and will be lost if
                                      //     the code is regenerated.
                                      // </auto-generated>
                                      //------------------------------------------------------------------------------
                                  
                                      using NSubstitute;
                                      using Temporalio.Activities;
                                  
                                      namespace Generator.Tests.ActivityMockGenerator
                                      {
                                          public partial class TestMocks
                                          {
                                              public Func<Task> MockRunAsync =
                                                  Substitute.For<Func<Task>>();
                                              public Func<Task> MockRunAsync2 =
                                                  Substitute.For<Func<Task>>();
                                  
                                              [Activity]
                                              public Task RunAsync()
                                              {
                                                  return MockRunAsync();
                                              }
                                      
                                              [Activity]
                                              public Task RunAsync2()
                                              {
                                                  return MockRunAsync2();
                                              }
                                          }
                                      }

                                      """;

        RunTest(input, expectedOutput, "TestMocks");
    }
    
    private void RunTest(string input, string expectedOutput, string className)
    {
        // arrange
        var syntaxTree = CSharpSyntaxTree.ParseText(input);
        Assert.Empty(syntaxTree.GetDiagnostics());

        var compilation = CSharpCompilation.Create(nameof(ActivityMockGeneratorTests), new[] { syntaxTree })
            .AddReferences(
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(Workflow).Assembly.Location)
            );

        // act
        var runResult = CSharpGeneratorDriver.Create(new ActivityMockCodeGenerator())
            .RunGenerators(compilation)
            .GetRunResult();

        // assert
        var outputFile = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith(className + "ActivityMock.g.cs"));
        Assert.Equal(expectedOutput, outputFile.GetText().ToString());
    }
}