using System.Linq;
using ActivityGenerator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Temporalio.Workflows;
using Xunit;

namespace Generator.Tests.ActivityGenerator;

public class ActivityGeneratorTests
{
    [Fact]
    public void GeneratesCorrectOutputForBasicActivity()
    {
        const string input = """
                             using System.Threading.Tasks;
                             using Temporalio.Activities;
                             using Temporalio.Generators.Activities;

                             namespace Generator.Tests.ActivityGenerator;

                             public class TestActivities
                             {
                                [Activity]
                                [GenerateActivityExtension]
                                public async Task RunMethod()
                                {
                                    await Task.Delay(1000);
                                }
                             }
                             """;

        const string expectedOutput = """
                                      //------------------------------------------------------------------------------
                                      // <auto-generated>
                                      //     This code was generated.
                                      //
                                      //     Changes to this file may cause incorrect behavior and will be lost if
                                      //     the code is regenerated.
                                      // </auto-generated>
                                      //------------------------------------------------------------------------------

                                      using Temporalio.Client;
                                      using Temporalio.Workflows;

                                      namespace Temporalio.Generators.Activities
                                      {
                                          public static partial class Activities
                                          {
                                              public static System.Threading.Tasks.Task ExecuteRunMethod(ActivityOptions options)
                                              {
                                                  return Workflow.ExecuteActivityAsync((Generator.Tests.ActivityGenerator.TestActivities x) =>  x.RunMethod(), options);
                                              }
                                          }
                                      }
                                      
                                      """;

        RunTest(input, expectedOutput);
    }

    [Fact]
    public void GeneratesCorrectOutputForActivityWithStringReturnType()
    {
        const string input = """
                             using System.Threading.Tasks;
                             using Temporalio.Activities;
                             using Temporalio.Generators.Activities;

                             namespace Generator.Tests.ActivityGenerator;

                             public class TestActivities
                             {
                                [Activity]
                                [GenerateActivityExtension]
                                public async string RunMethod()
                                {
                                    return "hello";
                                }
                             }
                             """;

        const string expectedOutput = """
                                      //------------------------------------------------------------------------------
                                      // <auto-generated>
                                      //     This code was generated.
                                      //
                                      //     Changes to this file may cause incorrect behavior and will be lost if
                                      //     the code is regenerated.
                                      // </auto-generated>
                                      //------------------------------------------------------------------------------

                                      using Temporalio.Client;
                                      using Temporalio.Workflows;

                                      namespace Temporalio.Generators.Activities
                                      {
                                          public static partial class Activities
                                          {
                                              public static System.Threading.Tasks.Task<string> ExecuteRunMethod(ActivityOptions options)
                                              {
                                                  return Workflow.ExecuteActivityAsync((Generator.Tests.ActivityGenerator.TestActivities x) =>  x.RunMethod(), options);
                                              }
                                          }
                                      }
                                      
                                      """;

        RunTest(input, expectedOutput);
    }

    [Fact]
    public void GeneratesCorrectOutputForActivityWithTaskTStringReturnType()
    {
        const string input = """
                             using System.Threading.Tasks;
                             using Temporalio.Activities;
                             using Temporalio.Generators.Activities;

                             namespace Generator.Tests.ActivityGenerator;

                             public class TestActivities
                             {
                                [Activity]
                                [GenerateActivityExtension]
                                public async Task<string> RunMethod()
                                {
                                    return "hello";
                                }
                             }
                             """;

        const string expectedOutput = """
                                      //------------------------------------------------------------------------------
                                      // <auto-generated>
                                      //     This code was generated.
                                      //
                                      //     Changes to this file may cause incorrect behavior and will be lost if
                                      //     the code is regenerated.
                                      // </auto-generated>
                                      //------------------------------------------------------------------------------

                                      using Temporalio.Client;
                                      using Temporalio.Workflows;

                                      namespace Temporalio.Generators.Activities
                                      {
                                          public static partial class Activities
                                          {
                                              public static System.Threading.Tasks.Task<string> ExecuteRunMethod(ActivityOptions options)
                                              {
                                                  return Workflow.ExecuteActivityAsync((Generator.Tests.ActivityGenerator.TestActivities x) =>  x.RunMethod(), options);
                                              }
                                          }
                                      }
                                      
                                      """;

        RunTest(input, expectedOutput);
    }

    [Fact]
    public void GeneratesCorrectOutputForActivityWithIntReturnType()
    {
        const string input = """
                             using System.Threading.Tasks;
                             using Temporalio.Activities;
                             using Temporalio.Generators.Activities;

                             namespace Generator.Tests.ActivityGenerator;

                             public class TestActivities
                             {
                                [Activity]
                                [GenerateActivityExtension]
                                public async int RunMethod()
                                {
                                    return 42;
                                }
                             }
                             """;

        const string expectedOutput = """
                                      //------------------------------------------------------------------------------
                                      // <auto-generated>
                                      //     This code was generated.
                                      //
                                      //     Changes to this file may cause incorrect behavior and will be lost if
                                      //     the code is regenerated.
                                      // </auto-generated>
                                      //------------------------------------------------------------------------------

                                      using Temporalio.Client;
                                      using Temporalio.Workflows;

                                      namespace Temporalio.Generators.Activities
                                      {
                                          public static partial class Activities
                                          {
                                              public static System.Threading.Tasks.Task<int> ExecuteRunMethod(ActivityOptions options)
                                              {
                                                  return Workflow.ExecuteActivityAsync((Generator.Tests.ActivityGenerator.TestActivities x) =>  x.RunMethod(), options);
                                              }
                                          }
                                      }
                                      
                                      """;

        RunTest(input, expectedOutput);
    }

    [Fact]
    public void GeneratesCorrectOutputForActivityWithTaskTIntReturnType()
    {
        const string input = """
                             using System.Threading.Tasks;
                             using Temporalio.Activities;
                             using Temporalio.Generators.Activities;

                             namespace Generator.Tests.ActivityGenerator;

                             public class TestActivities
                             {
                                [Activity]
                                [GenerateActivityExtension]
                                public async Task<int> RunMethod()
                                {
                                    return 42;
                                }
                             }
                             """;

        const string expectedOutput = """
                                      //------------------------------------------------------------------------------
                                      // <auto-generated>
                                      //     This code was generated.
                                      //
                                      //     Changes to this file may cause incorrect behavior and will be lost if
                                      //     the code is regenerated.
                                      // </auto-generated>
                                      //------------------------------------------------------------------------------

                                      using Temporalio.Client;
                                      using Temporalio.Workflows;

                                      namespace Temporalio.Generators.Activities
                                      {
                                          public static partial class Activities
                                          {
                                              public static System.Threading.Tasks.Task<int> ExecuteRunMethod(ActivityOptions options)
                                              {
                                                  return Workflow.ExecuteActivityAsync((Generator.Tests.ActivityGenerator.TestActivities x) =>  x.RunMethod(), options);
                                              }
                                          }
                                      }
                                      
                                      """;

        RunTest(input, expectedOutput);
    }

    [Fact]
    public void GeneratesCorrectOutputForActivityWithTaskTRecordReturnType()
    {
        const string input = """
                             using System.Threading.Tasks;
                             using Temporalio.Activities;
                             using Temporalio.Generators.Activities;

                             namespace Generator.Tests.ActivityGenerator;

                             public class TestActivities
                             {
                                [Activity]
                                [GenerateActivityExtension]
                                public async Task<TestRecord> RunMethod()
                                {
                                    return new TestRecord();
                                }
                             }
                             
                             public record TestRecord();
                             
                             """;

        const string expectedOutput = """
                                      //------------------------------------------------------------------------------
                                      // <auto-generated>
                                      //     This code was generated.
                                      //
                                      //     Changes to this file may cause incorrect behavior and will be lost if
                                      //     the code is regenerated.
                                      // </auto-generated>
                                      //------------------------------------------------------------------------------

                                      using Temporalio.Client;
                                      using Temporalio.Workflows;

                                      namespace Temporalio.Generators.Activities
                                      {
                                          public static partial class Activities
                                          {
                                              public static System.Threading.Tasks.Task<Generator.Tests.ActivityGenerator.TestRecord> ExecuteRunMethod(ActivityOptions options)
                                              {
                                                  return Workflow.ExecuteActivityAsync((Generator.Tests.ActivityGenerator.TestActivities x) =>  x.RunMethod(), options);
                                              }
                                          }
                                      }
                                      
                                      """;

        RunTest(input, expectedOutput);
    }
    
    [Fact]
    public void GeneratesCorrectOutputForActivityWithInput()
    {
        const string input = """
                             using System.Threading.Tasks;
                             using Temporalio.Activities;
                             using Temporalio.Generators.Activities;

                             namespace Generator.Tests.ActivityGenerator;

                             public class TestActivities
                             {
                                [Activity]
                                [GenerateActivityExtension]
                                public async Task RunMethod(TestRecord input)
                                {
                                    await Task.Delay(1000);
                                }
                             }
                             
                             public record TestRecord();
                             
                             """;

        const string expectedOutput = """
                                      //------------------------------------------------------------------------------
                                      // <auto-generated>
                                      //     This code was generated.
                                      //
                                      //     Changes to this file may cause incorrect behavior and will be lost if
                                      //     the code is regenerated.
                                      // </auto-generated>
                                      //------------------------------------------------------------------------------

                                      using Generator.Tests.ActivityGenerator;
                                      using Temporalio.Client;
                                      using Temporalio.Workflows;

                                      namespace Temporalio.Generators.Activities
                                      {
                                          public static partial class Activities
                                          {
                                              public static System.Threading.Tasks.Task ExecuteRunMethod(Generator.Tests.ActivityGenerator.TestRecord input, ActivityOptions options)
                                              {
                                                  return Workflow.ExecuteActivityAsync((Generator.Tests.ActivityGenerator.TestActivities x) =>  x.RunMethod(input), options);
                                              }
                                          }
                                      }
                                      
                                      """;

        RunTest(input, expectedOutput);
    }

    [Fact]
    public void GeneratesCorrectOutputForActivityWithMultipleInput()
    {
        const string input = """
                             using System.Threading.Tasks;
                             using Temporalio.Activities;
                             using Temporalio.Generators.Activities;

                             namespace Generator.Tests.ActivityGenerator;

                             public class TestActivities
                             {
                                [Activity]
                                [GenerateActivityExtension]
                                public async Task RunMethod(TestRecord input, string input2)
                                {
                                    await Task.Delay(1000);
                                }
                             }
                             
                             public record TestRecord();
                             
                             """;

        const string expectedOutput = """
                                      //------------------------------------------------------------------------------
                                      // <auto-generated>
                                      //     This code was generated.
                                      //
                                      //     Changes to this file may cause incorrect behavior and will be lost if
                                      //     the code is regenerated.
                                      // </auto-generated>
                                      //------------------------------------------------------------------------------

                                      using System;
                                      using Generator.Tests.ActivityGenerator;
                                      using Temporalio.Client;
                                      using Temporalio.Workflows;

                                      namespace Temporalio.Generators.Activities
                                      {
                                          public static partial class Activities
                                          {
                                              public static System.Threading.Tasks.Task ExecuteRunMethod(Generator.Tests.ActivityGenerator.TestRecord input, string input2, ActivityOptions options)
                                              {
                                                  return Workflow.ExecuteActivityAsync((Generator.Tests.ActivityGenerator.TestActivities x) =>  x.RunMethod(input, input2), options);
                                              }
                                          }
                                      }
                                      
                                      """;

        RunTest(input, expectedOutput);
    }

     [Fact]
    public void GeneratesCorrectOutputForStaticActivity()
    {
        const string input = """
                             using System.Threading.Tasks;
                             using Temporalio.Activities;
                             using Temporalio.Generators.Activities;

                             namespace Generator.Tests.ActivityGenerator;

                             public static class TestActivities
                             {
                                [Activity]
                                [GenerateActivityExtension]
                                public async Task RunMethod(TestRecord input, string input2)
                                {
                                    await Task.Delay(1000);
                                }
                             }
                             
                             public record TestRecord();
                             
                             """;

        const string expectedOutput = """
                                      //------------------------------------------------------------------------------
                                      // <auto-generated>
                                      //     This code was generated.
                                      //
                                      //     Changes to this file may cause incorrect behavior and will be lost if
                                      //     the code is regenerated.
                                      // </auto-generated>
                                      //------------------------------------------------------------------------------

                                      using System;
                                      using Generator.Tests.ActivityGenerator;
                                      using Temporalio.Client;
                                      using Temporalio.Workflows;

                                      namespace Temporalio.Generators.Activities
                                      {
                                          public static partial class Activities
                                          {
                                              public static System.Threading.Tasks.Task ExecuteRunMethod(Generator.Tests.ActivityGenerator.TestRecord input, string input2, ActivityOptions options)
                                              {
                                                  return Workflow.ExecuteActivityAsync(() => Generator.Tests.ActivityGenerator.TestActivities.RunMethod(input, input2), options);
                                              }
                                          }
                                      }
                                      
                                      """;

        RunTest(input, expectedOutput);
    }

    private void RunTest(string input, string expectedOutput)
    {
        // arrange
        var syntaxTree = CSharpSyntaxTree.ParseText(input);
        Assert.Empty(syntaxTree.GetDiagnostics());

        var compilation = CSharpCompilation.Create(nameof(ActivityGeneratorTests), new[] { syntaxTree })
            .AddReferences(
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(Workflow).Assembly.Location)
            );

        // act
        var runResult = CSharpGeneratorDriver.Create(new ActivityCodeGenerator())
            .RunGenerators(compilation)
            .GetRunResult();

        // assert
        var outputFile = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("TemporalActivityExtensions.g.cs"));
        Assert.Equal(expectedOutput, outputFile.GetText().ToString());
    }
}
