name: Generate WorkflowGenerator nuget package

on:
  workflow_dispatch: {}

jobs:
  generate-csharp-client:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: |
          dotnet build ./src/WorkflowGenerator/WorkflowGenerator.csproj --configuration Release
        
      - name: Publish
        run: dotnet nuget push ./src/WorkflowGenerator/bin/Release/*.nupkg  --source "GH" --api-key ${{secrets.GITHUB_TOKEN}}